### ISSUE TITLE
It's broken on non-windows OS

### ISSUE THREAD

**Issue by capnm** [BastiaanOlij/gdtest#1]
I think you should do something like
```
cpp_bindings_library = 'godot-cpp'
…
        cpp_bindings_library += …
…
env.Append(LIBS=[cpp_bindings_library], LIBPATH=['#' + cpp_bindings_path + '/bin'])
```
in your Sconscript.

( rtfm https://scons.org/doc/3.0.1/HTML/scons-user/ch04s03.html ;-)

**Comment by BastiaanOlij** [comment]
Ugh! that's bitten me before! I'll find some time tonight to deal with that, thanks

**Comment by ghost** [comment]
Did you forget to close this or it's not fixed yet? :stuck_out_tongue:

**Comment by BastiaanOlij** [comment]
@Noshyaar should be good now but I can't test it :) Hoping for someone to give me a thumbs up if my changes worked:)

**Comment by ghost** [comment]
It works on Linux for me afaik. 👍
